### ISSUE TITLE
What should I do to avoid sudden temperature spikes on the screen?

### ISSUE THREAD

**Issue by goga1978** [Ralim/IronOS#1824] opened 2023-10-13 00:43 UTC
Hello everyone.

1. It is necessary to enter a list of BC2, K, KU and other stings.
2. Make a normal calibration of the tip by temperature points (450, 350, 250, 150)
3. Enter the screen refresh time 0.5sec, 1 sec, 2 sec. So that the readings do not jump.
4. Enter filtering, say we take 20 values, sort in ascending order and take the value from the middle
(246, 246 , 247, 247, 248, 248 , 248 , 249 , 249, 250, 250) = 248.

**Comment by Ralim** [comment] 2023-10-15 10:53
Closed as duplicate of #1688

**Closed by Ralim** 2023-10-15 10:53 UTC
Labels: enhancement
