### ISSUE TITLE
Firmware does not work on dfu 3.47 on ts100

### ISSUE THREAD

**Issue by Cupitori** [Ralim/IronOS#1199] opened 2022-01-26 20:47 UTC
**Describe the bug**
After flashing v2.16 on TS100 with DFU 3.47 the iron becomes a brick.
**To Reproduce**
1. Take brand new TS100 with DFU 3.47
2. Download TS100.zip file from the v2.16 release Unzip TS100.zip
3. Press button A and connect TS100 to windows PCCopy TS100_RU.hex to TS100
4. the firmware was completed successfully
4. Power on
5. the screen is black

**Expected behavior**

**Details of your device:**
 
 Device: TS100Release: 
Can't get hardware release, late 2021 model, DFU 3.47
Power adapter being used: YH24-3

**Additional context**

After flashing the iron still enters DFU mode.
Default firmware v2.18 does not work as well and causes the same behavior.
immediately 2.20 was not flashed, I flashed the firmware in order from the oldest to 2.20
Default firmware v2.20 works correctly. Device is work.

**Comment by discip** [comment] 2022-01-26 21:17
Good evening @Cupitori.
# Please search in the already existing issues before opening a new one. 😊

If I am right, then you are at least the 4th one addressing this topic!

https://github.com/Ralim/IronOS/discussions/1155#discussioncomment-2032230
https://github.com/Ralim/IronOS/issues/1170
https://github.com/Ralim/IronOS/issues/1177

**Comment by Ralim** [comment] 2022-01-26 21:52
Closing this issue as its a duplicate of existing ones and notes on the release page.

**Closed by Ralim** 2022-01-26 21:52 UTC
