### ISSUE TITLE
Bugs with MHP30

### ISSUE THREAD

**Issue by RWDZ** [Ralim/IronOS#1613] opened 2023-03-09 14:41 UTC
Device: MHP30

Something strange is happening with the sleep mode settings. The sleep mode is activated significantly earlier than set in the settings. When I set the sleep mode for 3 minutes, sleep started after a minute. When I set the sleep mode for 10 minutes, sleep started after a 3 minute. After that, the heater refused to exit sleep mode at all. The display constantly blinked despite attempts to press different buttons. I turn on to show sleep mode as blinked display.

The heater always turns on with a red backlight. The heater has a tri-color LED installed, which changes color depending on the temperature on the original firmware. On the last Iros OS firmware, the color is always red. Original firmware use next colors:
Below 50		Green
50-80		Yellow
80-200		White
Above 200	Red

**Comment by discip** [comment] 2023-03-10 22:30
@RWDZ
Maybe this is related to #1570?

**Comment by RWDZ** [comment] 2023-03-11 16:29
Perhaps this is a manifestation of the same problem. But that does not change the essence of the problem. The stock firmware turned out to be even better in this case. I do not recommend anyone to use Iron OS with MHP30 now.

**Comment by discip** [comment] 2023-03-11 16:34
Can you confirm that your post could be declared as a duplicate of the mentioned one?
If so, would you mind if we close this issue, mark it as a duplicate and reference it in #1570, so there is less noise. 😊

**Closed** 2023-06-29 22:13 UTC
Labels: duplicate
