### ISSUE TITLE
MHP30 Reflow Profile

### ISSUE THREAD

**Issue by nizce** [Ralim/IronOS#1619] opened 2023-03-13 00:20 UTC
Hi!
Great firmware/OS, loving it so far :)

**Is your feature request related to a problem? Please describe.**
Not a problem, but a useful feature for such a device

**Describe the solution you'd like**
It'd be great if it was possible to add a reflow profile for the MHP30.
For example: Possibility to add: duration, target temp and max increase of degrees/sec for the four stages/zones: pre-heat, soak, reflow & cooling. 

**Describe alternatives you've considered**
None really except using a timer and only focus on reflow zone/stage :)

**Additional context**
None

**Comment by discip** [comment] 2023-03-14 23:29
Closing as this is a duplicate of #1201.

**Closed by discip** 2023-03-14 23:29 UTC
Labels: enhancement
