### ISSUE TITLE
Alternative bootloader?

### ISSUE THREAD

**Issue by perillamint** [Ralim/IronOS#25] opened 2017-07-14 08:37 UTC
Quite out of scope of this project, but as all we know, default DFU bootloader is quite unstable. It does not work "well" on Mac or Linux.

I think alternative bootloader which supports [standard DFU protocol](http://wiki.openmoko.org/wiki/USB_DFU_-_The_USB_Device_Firmware_Upgrade_standard) can help firmware development in Linux or other non-Windows systems.

Could we build alternative bootloader which supports DFU protocol other then default buggy USB-MSD DFU?

**Comment by Ralim** [comment] 2017-07-14 08:50
Hi,
I'm completely open to building an alternate bootloader for the unit. I toyed with this before, however, most people seemed to prefer the MSD based bootloader for ease of use. Also considering the number of emails, messages and issues that are similar to #23 I don't overly want to advertise it too heavily. 

It would certainly be possible to implement an alternate bootloader & then have a conversion firmware that swapped out the bootloaders. If you would find this useful though, I can start a GitHub project for this and try and get a replacement bootloader up and going.

**Comment by perillamint** [comment] 2017-07-18 03:04
I think I could get some time to tinker with iron firmware 1-3 months later. (need to source another iron for SWD pin soldering, get enough time to spend hacking new bootloader, etc)

However I have one question before wiping out bootloader of my iron (or another TS-100): Could I get back into stock system when I flash "DO NOT FLASH_Flash Backup.hex" using ST-Link?

**Comment by Ralim** [comment] 2017-08-04 05:09
So I'm thinking of forking [dapboot](https://github.com/devanlai/dapboot) and working to get that running on the iron. So that we can use web-dfu along with the normal dfu-util to update the iron.

Mostly going to need a fair bit of testing before I push anything too publicly.... Dont want to brick irons :)

**Comment by vifino** [comment] 2017-08-04 20:15
I am also in favor of "normal" DFU, to be used with dfu-util. Much easier, IMO.
Once mine arrives, I'll be happy to test. Got JTAG/SWD adapters and everything, so in case something goes seriously wrong, I'll be able to recover.

**Comment by Ralim** [comment] 2017-08-04 23:14
the dapboot implementation supports both web based and the normal dfu-util tool :)
Awesome, will be good to have another tester :)

**Comment by Maartenwut** [comment] 2017-08-05 05:22
I'll be glad to have another bootloader as well - I'm in for testing!

**Comment by perillamint** [comment] 2017-08-12 07:14
I purchased Olimex STM32-H103 board and flashed that "DO NOT FLASH_Flash Backup.hex". After some configuration (Pull down PC11), It boots successfully on that board.

I think I could start bootloader development on this board rather then directly on iron.

**Comment by Ralim** [comment] 2017-08-12 07:51
Hey,
Yeah I have been using one of the blue common f103 breakout boards to work on. I just haven't had much time. The only issue I could see with this is getting the bootloader working well without the crystal. As I'm not sure if it *just works* at room temperature, or if they are performing a calibration on the internal oscillator. Since I think the internal oscillator tolerance is wider than USB technically requires.

I am planning to fork dapboot for the iron as it supports the web dfu, and see if it can run without the crystal. (The ts100 *does not* have any crystals or timing references fitted)

**Comment by perillamint** [comment] 2017-08-12 10:36
@Ralim I tested it using rcc_clock_setup_in_hsi_out_48mhz() instead of     rcc_clock_setup_in_hse_8mhz_out_72mhz(). It enumerates well and works well.

Host used: Dell XPS 9550

**Comment by Ralim** [comment] 2017-08-12 11:12
Awesome, if you want to develop it in a branch of this repo I can give you push access if that's easier? (Lets us keep the code for the iron fairly central). Thoughts ?

**Comment by perillamint** [comment] 2017-08-12 14:16
BTW, I tried to load original firmware using DAPBoot. It *seems* loads find but Stock firmware's USB does not enumerate with error -71

I suspect clock configuration but I'm not sure. Does anyone know any clue about this?

**Comment by perillamint** [comment] 2017-08-12 14:27
Hey @Ralim, Could you make documentation about pads on small STM32F103 board in TS100?

I'm planning to get another TS100 in September and that information will be great help

**Comment by Maartenwut** [comment] 2017-08-12 18:18
![untitled-1](https://user-images.githubusercontent.com/17366381/29243280-5d4a8ed4-7f9b-11e7-8547-0dfb2c55ac3c.png)

**Comment by vifino** [comment] 2017-08-12 19:17
Wow!
Looks like some progress happened!

My iron will be here in the next couple of days - tell me if you need testers.

**Comment by Ralim** [comment] 2017-08-13 02:05
Hi all,
@perillamint I'll try and document the pads for you. I recently picked up another one from work for working on the bootloader. I'm 99% sure it will be the clock configuration. The firmware expects the bootloader to setup the clocks for 72MHz. Also ensure the bootloader is compiling and fitting, as the firmware expects to start at 0x8004000 off memory (so therefore size of the bootloader should be < 0x4000).

The 4 pads on the bottom of the board are GND,VCC,SWDIO,SWCLK. In that picture off memory they are GND in bottom left, vcc in top left, and the other two are clk/dio (i just swapped jumpers till it worked).

Once we get the bootloader up and running we can make a conversion firmware that re-flashes it using the old bootloader.

**Comment by perillamint** [comment] 2017-08-13 03:23
I dumped rcc memory regions and it differ quite a bit. I'll try document this changes and apply this hack on bootloader.

I think this change could not merged back into dapboot mainline, so I think only option is fork and maintain dapboot for TS100.

**Comment by Ralim** [comment] 2017-08-13 03:29
Yeah, I agree that we will have to maintain our own fork of dapboot.
Should not be too hard to maintain, and will just need to keep an eye on what happens to it.

**Comment by perillamint** [comment] 2017-08-16 12:42
My backup iron arrived today. I soldered ST-Link and flashed my bootloader.

It successfully loads stock firmware (without USB) and OLED shows text on it. However when I put your firmware, it does not turn on display.

Do you have any idea about it?

**Comment by Ralim** [comment] 2017-08-16 13:06
Interesting, 
I'm using the same initialisation code as they do for the clocks etc, does your code jump to 0x4000?

Not massively sure what would cause it to hang, I'm happy to try on my development iron shortly (hectic week at the moment). 

Can I ask which firmware you loaded? Also if you can inspect the program counter on the crash. My current best guess would be that the bootloader is not placing the firmware at 0x4000 offset so when my code sets the nvic to that offset the interrupts get invalid addresses for the Irq handlers. 

Off a very vague memory the bootloader uses 0x8000 as it's loading point instead. I probably could technically drop the nvic remap in my code as I'm fairly sure the official firmware does it as well. This would also make sense as I make heavy use of the interrupts where as their code was entirely software polling based except for the usb connection off memory.

**Comment by perillamint** [comment] 2017-08-16 14:00
I succeeded! The problem was this: https://github.com/perillamint/dapboot/commit/9966fbd641f371386cdb7a19c8ccacbd7eb4daf1

TS100 stock firmware assumes its bootloader turned on some STM32 peripherals. After I turn on USB and I2C, it works just fine.

**Comment by perillamint** [comment] 2017-08-16 14:02
Now, we need some way to flash patched DAPBoot bootloader using stock bootloader.

**Comment by perillamint** [comment] 2017-08-16 14:23
BTW, DAPBoot is not quite "fool proof" -- it could brick itself when user put large blob on it. I think we should mitigate this problem.

**Comment by perillamint** [comment] 2017-08-17 15:26
I fixed self-brick issue with https://github.com/perillamint/dapboot/commit/e3a5a633d44b422397f8cb4b01636647ab44d84a this commit.

IMHO, we could do some beta(or alpha?)-testing from now.

What do you think @Ralim?

**Comment by Ralim** [comment] 2017-08-17 23:52
Hi,
Can you confirm if this bootloader protects you from trying to flash to anywhere below 0x8004000?
I'm happy to make up some conversion firmware that would re-flash the bootloader. Just rather busy at the moment.

**Comment by perillamint** [comment] 2017-08-18 01:34
@Ralim Since DAPBoot does not support DfuSe, I don't think user could put negative number on `current_dfu_offset`

https://github.com/devanlai/dapboot/blob/master/src/dfu.c#L232

However, if we need real fool-proof, I think I could extend this patch(https://github.com/perillamint/dapboot/commit/e3a5a633d44b422397f8cb4b01636647ab44d84a) little bit to implement only allows flashing command within this address range: (0x08000000 + APP_BASE) - (0x08000000 + FLASH_SIZE)

**Comment by perillamint** [comment] 2017-08-18 02:22
BTW, I think I could work on bootloader flasher in next week (or 2-weeks later, depends on my other works :)). 

Since stock bootloader is quite fragile, I think bootloader flasher should implement some safety mechanism like payload checksum check to protect devices from "hard brick" scenario.

Another question is: Should we "merge" DAPBoot fork into your firmware repository? or should we create GH group to maintain TS100 related repos? What do you think @Ralim?

**Comment by Ralim** [comment] 2017-08-18 02:42
Good to hear, I wasn't sure of memory how much protection it had for trying to flash the wrong thing :) Mostly just asking :)

It might be worth adding the extra protection just in case, can't hurt to add it :)

Yeah, I'm hoping I'll have more time soon to keep working on the firmware for this, just been a bit too busy with working. The .HEX file itself has a rough checksum in it, and the dfuse protocol has checksums from memory. The biggest issue is not corruption in the file transfer but just getting the file there, which the dfuse *should* solve.

We cant really stop people flashing the wrong files, we just have to make it so that those diles cannot break the dfu bootloader :)

I'm thinking of making a Github org for community E-design products since I'm slowly working on a codebase for the ES120 as well. Then we could use that to organise all the future repositories? (Might not move this one for a bit since this link has been shared a fair bit).  Thoughts?

**Comment by perillamint** [comment] 2017-08-18 06:18
I think cloning this repo to new group and put migration notice on this repo will be enough for redirecting people to new repo.

BTW, I'm planning to buy ES120 next month. It looks quite nice. I guess this DAPBoot port will work on ES120 without huge effort. I hope they didn't lock flash on ES120 like TS100 did. :)

**Comment by perillamint** [comment] 2017-08-18 06:23
Just FYI, I'm trying to mainline some of the patches from DAPBoot fork to original DAPBoot. Although we could not mainline all of our changesets, some parts like flash overrun protection will be helpful to other hardware.

https://github.com/devanlai/dapboot/issues

**Comment by Ralim** [comment] 2017-08-18 08:48
Hi @perillamint 
I would have to transfer the repository rather than clone because I need to keep the links working, considering the number of people who seem to have issues finding the *releases* page I don't want to make them have to find a new home for it too :stuck_out_tongue: 
Also, would need to ensure all links transfer correctly and don't break.

Heh, the TS100 flash is not locked afaik (wasn't locked on any of my units?). The ES120 does not have the debug pins broken out, and also disables JTAG+SWD by default which makes it much harder. Also, all the wiring is done to generic gpio so have to use software bit-bang for all the comms which sucks.

Good idea to mainline the changes. Though the other option here would be to just have a build option for dapboot and not need to do different repositories entirely? (Thinking if all the changes basically end up mainline except for OLED support)

**Comment by EricJanVanDenBogaard** [comment] 2017-08-19 09:23
Never had any problems with the boot loader on my Mac Book Pro,
is it possible to revert to the factory firmware with a new/different boot loader ?

**Comment by Ralim** [comment] 2017-08-20 10:47
You have been lucky :smile: It seems to be really hit and miss as to who has it work perfectly and who has issues.

The new DFU should completely support the factory firmware, they are separate pieces of code entirely. Eventually, we will also provide code to let you swap back as well just in case the newer factory firmware has any issues.

**Comment by thanks4opensource** [comment] 2017-08-22 14:53
Just to clarify: Does flashing the Ralim (or other) firmware .hex file also flash/overwrite the DFU? I.e., if the .hex file is bad or something goes wrong with the flash can you end up with not only a non-working iron due to corrupted firmware, but a bricked one that can't be re-flashed successfully?

I looked at a binary file converted from 1.16.3 TS100.hex and didn't find the strings "DFU" or "3.43" anywhere in it. Those characters display on my TS100's LCD both before and after flashing so I assume the ascii is somewhere in its flash memory (unless it's maybe just a bitmap). That implies "no", but this wiki seems to say that flashing does overwrite the DFU.

If so -- and this is a naive suggestion which I'm sure you've already considered and rejected for technical reasons -- is there any way to specify the address ranges in the .hex to only flash the firmware and not the DFU? Are the address ranges page-aligned to the boundaries of the flash erase/write blocks? Is the DFU above or below the firmware in the memory map (is it even in the same address space?) or is interleaved in the middle?

Like I said, these are naive newby questions if someone has the time to answer them.

**Comment by vifino** [comment] 2017-08-22 15:30
@thanks4opensource It does not, so it shouldn't be possible to completely brick it without flashing the bootloader seperately first.
But even then, with a JTAG/SWD dongle, you should be able to recover, although that might take a while, depending on whether you are used to stuff like this, which I am guessing not.

The DFU is not able to overwrite itself, or at least shouldn't. Unsure of the default one.
That'd be such a bad idea, unless it's first action is to copy itself into memory or something. Don't quote me on this.
I am pretty sure it doesn't do that. If you read above, @perillamint says they are working on a bootloader flasher, which would be something you flash via the original DFU and just copies a payload into the bootloader region. Much safer.

Regarding location, the bootloader is first, as far as I know.

**Comment by thanks4opensource** [comment] 2017-08-22 16:13
Thanks for the education and allying my fears, @vifino 

I actually am doing a bunch of ARM/STM development over ST-LINK/SWD right now, although I'm a newbie to it. I'd like to hack on the TS100 firmware myself but the idea of flashing a binary (hex) and hoping for the best scares me. I'm used to having OpenOCD/GDB/etc and I don't like the thought of debugging with, at best, printfs to the LCD display as the only view into what's going wrong. I've read the stuff above, but the idea of opening the iron and soldering SWD access onto the pads is even scarier than flash-bricking it. ;)

Wish there could have been a debug port. Maybe a jumper to turn the USB connector into SWD via a custom-wired connector. But it's an end-user product and no reason for MiniDSO (or whoever is the actual manufacturer/designer -- I'm still confused by the whole Chinese chain of Alibaba/Taobao/Amazon/Ebay) to do anything like that. It's a miracle they open-sourced the firmware. I'm grateful for that -- it's the whole reason I bought one in the first place.

**Comment by perillamint** [comment] 2017-08-23 05:06
@thanks4opensource FYI: there is debug port. STM32 MCU board part has test pads on it and it is wired Vcc(3v3) GND SWCLK SWDAT. However, you must solder RESET pin on capacitor C17 since they're not broken out via test pads. Only that part (Soldering on C17) is tricky.

**Comment by perillamint** [comment] 2017-08-23 05:11
@vifino Original DAPBoot has a bug that may brick itself when user puts large enough payload which could damage bootloader, but I fixed that bug and mainlined fix for that.

Except for that bug, there is no way (unless another bug discovered) to go back below 0x08004000, where bootloader sits on flash, so I think it could be considered as "safe for normal use"

**Comment by Ralim** [comment] 2017-08-23 08:36
@perillamint You don't have to solder the reset pin if you use software reset on the SWD link to reset the mcu for programming :smile:. One less thing to solder :)

I think it would be entirely safe for use for all practical use cases. At least in this product, they gave us the debugging pins to connect to... 
"They" is miniware which is owned by e-Design as far as I understand the hierarchy.

**Comment by thanks4opensource** [comment] 2017-08-23 15:46
Just want to say I understand about the debug test pads being brought out, and am very impressed that miniware/e-Design/whoever was so open with both the hardware and firmware. I voted for them with my money! ;)

When I said "Wish there could have been a debug port" I meant a physical jack/connector. Sorry I wasn't clear about that. And I understand why physical size constraints and target market goals make my wish impractical.

 Very glad all of you were able to use the pads for development and give the rest of us your firmware/bootloader/etc. code. Thank you! As for me, at my current (low) skill level I'm not comfortable performing soldering brain surgery on my new, semi-expensive toy.

**Comment by vifino** [comment] 2017-08-24 11:39
@perillamint Thanks for clarification, I already knew that you fixed it before, I just wondered about the default one, the one that gets shipped from the factory.

I have no doubts that your fork will be much better than the original DFU, safety-wise and usability-wise (at least for Linux/Mac users).
I'll happily try to flash it, as soon as you got a flashing firmware that just writes dapboot into the bootloader region. Maybe not as the first one. 😄

**Comment by perillamint** [comment] 2017-08-26 13:14
I think I could start working on bootloader flasher from Monday. I'm considering I should add USB CDC-ACM console for user interaction (check payloads SHA256sum, confirm flash using some crude Y/N prompt, show flashing progress, confirm it should wipe out itself to enforce next boot mode to bootloader, etc).

I want to hear comment about this. Will it helpful or not?

**Comment by thanks4opensource** [comment] 2017-08-26 16:13
@perillamint -- Those are very good features.

**Comment by vifino** [comment] 2017-08-26 16:54
@perillamint It definitly sounds very useful.

**Comment by Ralim** [comment] 2017-08-27 02:14
@perillamint I wouldn't worry about the USB-CDC implementation, but would instead just print everything to the OLED and use the buttons for confirmation. That way the user doesn't need to bother trying to get the CDC port working just to be able to continue with the flash.

Verifying the checksum would be a good idea, and also verify it again once its been flashed as well.

You should be able to technically load the entire flasher into ram to speed up the process as well.

You can just set the magic key for entering into dapboot (RTC registers) rather than needing to wipe itself out :)

**Comment by perillamint** [comment] 2017-08-27 16:28
@Ralim I considered using OLED for verification process but I worry about it is not suitable for displaying full SHA256sum of payload.

Maybe RTC is much more suitable for bootloader flag rather than erasing 0x08004000.

**Comment by Ralim** [comment] 2017-08-28 09:13
You don't strictly need to show the entire hash, even if you just showed the last part then it would give a confidence boost. Or you could use a crc32 which will fit on the screen?

**Comment by EricJanVanDenBogaard** [comment] 2017-08-29 22:30
only thing i noticed is on my macbook, when i "eject" the TS100 with the OS option, it boots again when you're not fast enough to pull the plug. But i don't see this as a problem, when i have to use it by usb for updates. (i hope for a future USB-C version of the TS100, i think the non polarity plug feature a nice feature for that alone worth it)

**Comment by perillamint** [comment] 2017-09-17 10:47
I started working on BL flasher. Currently, I'm porting OLED driver for libopencm3

http://github.com/perillamint/ts100-bl-flasher

**Comment by perillamint** [comment] 2017-09-19 16:12
I successfully ported OLED driver. Now, I have to integrate button input and CRC32 generator before first "beta" release.

Also, I think my driver port could work in DAPBoot since they share same foundation(libopencm3)

**Comment by vifino** [comment] 2017-09-19 17:03
Very nice, @perillamint! I look forward to progress there!

Poke me if/when you need a tester. I would like an above-50/50 chance of success, however! ;)

**Comment by perillamint** [comment] 2017-09-19 17:20
@vifino I just finished BL flasher! :)

However, I think I could polish bootloader "Little bit more": Utilize OLED to display it is active or not.

After that, I think I could do some kind of "beta testing". :)

**Comment by perillamint** [comment] 2017-09-19 17:59
Bad news: DAPBoot uses old version of libopencm3, so my driver port is incompatible. I think it takes awhile to make DAPBoot utilize OLED screen.

BTW, I think my bootloader port is "functional", so I think I could release it.

**Comment by perillamint** [comment] 2017-09-19 18:45
https://github.com/perillamint/ts100-bl-flasher/releases/tag/1.0.0

I released bootloader flasher with two `payload.rom` variants: Stock and DAPBoot.

I tested it

**Comment by vifino** [comment] 2017-09-19 21:31
I'll flash it after I cleaned up my mess here. Will be in a couple hours at max.

**Comment by vifino** [comment] 2017-09-20 02:03
@perillamint  Oops, forgot to report back.

It flashed successfully, DAPBoot loads. Now to flash back Ralim's firmware.

**Comment by vifino** [comment] 2017-09-20 02:11
@perillamint Having a bit of trouble flashing the firmware...
```
Opening DFU capable USB device...
ID 0483:df11
Run-time device DFU version 0110
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuERROR, status = 7
dfuERROR, clearing status
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0110
Device returned transfer size 1024
Copying data from PC to DFU device
Download        [=================        ]  71%        49152 bytes failed!
state(10) = dfuERROR, status(7) = Programmed memory failed verification
```

**Comment by vifino** [comment] 2017-09-20 02:13
Reflashing the flasher fails as well... Not great. :(

**Comment by Ralim** [comment] 2017-09-20 02:31
@vifino Just for the sake of it, have you tried the web-based flashing tool?

https://devanlai.github.io/webdfu/dfu-util/

**Comment by vifino** [comment] 2017-09-20 02:33
@Ralim No, but I think I know what I am doing wrong. I was feeding dfu-util a .hex, not a binary.

**Comment by Ralim** [comment] 2017-09-20 02:41
Ah okay, yeah I don't currently push up .bin files to avoid confusion to users. 
There are converters around or I can provide some .bin files, later on, today if you need them.

**Comment by vifino** [comment] 2017-09-20 02:44
If you could poke me with a .bin, it'd be much appreciated, @Ralim. Currently, I am stuck with a windows machine, so there isn't much I can do.

**Comment by Ralim** [comment] 2017-09-20 02:52
[TS100.zip](https://github.com/Ralim/ts100/files/1316444/TS100.zip)
This is the V2.x release currently, so not perfect and may have some bugs but will let you get back to a working system hopefully and also let you test the bootloader.
Ill get some .bins for the latest 1.x release up tonight

**Comment by perillamint** [comment] 2017-09-20 03:25
I just woke up. @vifino Did it work well?

**Comment by Ralim** [comment] 2017-09-20 04:25
@perillamint Yes, I will make an organisation shortly, any idea what the best name is?
Currently not sure if eDesignOpenSource or something is worth it or? (Since don't want to use TS100 as it's not the only product really)

**Comment by perillamint** [comment] 2017-09-20 06:52
@Ralim Their company name is MiniDSO and they use MIN as their logo, so I suggest OpenMIN as our org name. I don't have any better idea about this. Out of naming creativity :'(

**Comment by Ralim** [comment] 2017-09-20 06:59
E-design is the parent to miniware aka minidso.
They use E-design for the es128, but miniware on the ts100 oddly.

So really not sure where to go :P

**Comment by perillamint** [comment] 2017-09-20 07:03
Maybe eDesignOSFW? or eDesignMod?

I got this two in my head now

**Comment by Ralim** [comment] 2017-09-20 07:04
eDesignOSS?

**Comment by perillamint** [comment] 2017-09-20 07:08
eDesignOSS. That looks good.

**Comment by perillamint** [comment] 2017-09-20 07:36
OK. I transfered my two repo into eDesignOSS org.

**Comment by Ralim** [comment] 2017-09-20 07:37
I'll transfer this one as soon, just need to set aside time to clean up some stuff first :)

**Comment by vifino** [comment] 2017-09-20 14:42
@Ralim It worked, thank you!

I do have a few issues with it, however. It seems very, very slow. Having to hold the buttons to get them to register (~0.5-1s at least), OLED visibly redrawing in settings. Other than that, it looks quite cool.

**Comment by vifino** [comment] 2017-09-20 14:49
@perillamint It did! Even my stupidity with trying to flash an intel hex encoded file instead of a binary didn't break it!
Thank you so much for your work! Made things much easier for me.

**Comment by perillamint** [comment] 2017-09-20 14:54
@vifino BTW, You could use http://hex2bin.sourceforge.net/ to convert hex to DFU-able bin. I converted recent 1.17.1 HEX into BIN. If you want a stable version, here is the file which I converted using hex2bin. https://www.dropbox.com/s/8p8i21az24q72zo/ts100.bin?dl=0

**Comment by vifino** [comment] 2017-09-20 15:15
@perillamint Thank you! I tried to do it using srecord, resulted in a huge binary, which obviously didn't work.
I really appreciate you handing me the bin, and of course your work. :)

**Comment by Ralim** [comment] 2017-10-03 01:59
@vifino Yeah sorry that bin file I uploaded was broken :/ oops.
I'm uploading .bin files of the newer firmware as I go as well, so feel free to try them :)

**Comment by vifino** [comment] 2017-10-03 05:00
@Ralim I'll surely do so. Probably not now though. It's 7 am and I've been up all night learning Lojban. ^_^

**Comment by vifino** [comment] 2017-10-03 17:24
@Ralim I've just tried it again, muuuuch better!
I like it a lot sofar. I am not sure if I imagine this, but could it heat just a tiny bit faster? It doesn't overshoot but reaches the temperature perfectly quite quickly. (On 24V)
The first half-second it gets confused, however, it displayed temperature way past 500 degrees celsius, but then it comes back to ~40 degrees and everything works fine again. I've ran a tip calibration before that.

I've also noticed that the help string for the calibration is cut off when it loops around.  Buffersize too small? You could determine the appropriate buffersize by using macros on all translation help strings, perhaps.

When there is a temperature warning, it seems to not be centered.

This 2.0 is quite an upgrade. One thing I did not find was the power source voltage calibration. Luckily my iron is quite accurate by default. I like the new idle screen. Having the advanced display not be used in the actual soldering mode is a bit unfortunate, because I'd like more information while soldering, not while in idle.

That's all the issues I could find in what limited testing I've done. Keep up the great work!

**Comment by Ralim** [comment] 2017-10-04 23:26
Hi @vifino,
Ah, okay looks like the PID has a little bit of wind up somewhere, I'll look into that.

 Also, another thing to note is that there is a rolling average filter on what is displayed on the screen, so when the screen is showing that it's at temp it has probably been at temp for around 1 second at the temperature sensor. This is done because the temp sensor is a little bit away from the tip itself, so the idea is that by the time that filter is showing it at temp, the tip should have equalized to that same temperature. The filter is set to around 0.8 seconds as this seems to be about the equalization time at a guess from asking some other people :smile: 

It shouldn't be showing way past 500 C normally unless the tip is unplugged. I'll try and re-create this locally as well.

Oops, thats probably a lack of padding in the wraparound :/. All the strings are using macros for string lengths etc. [I use strlen atm](https://github.com/Ralim/ts100/blob/v2.0/workspace/TS100/src/main.cpp#L303)

The centering of the temperature warning page is dependant on the length of the text used for the warning (language dependent). As currently all text is drawn left to right.

The 2.x firmware is still in alpha and voltage calibration is still on the todo list :smile: 

What would you like to see in the advanced soldering screen? More than happy to add one, just wasn't sure what should be there?

**Comment by thanks4opensource** [comment] 2017-10-05 03:30
@Ralim: Continuing to move off-subject for this issue, and you weren't asking me, anyway ;)  ...

The 2.0 alpha's PID behavior subjectively seems a little laggy compared to 1.7. Nothing I can prove, and maybe I'm imagining it. In terms of display, at least in "ADVDSP F" it seems like the power bar graph (which replaced the squiggly heater lines which always looked like bacon to me) used to briefly spike to full coming out of sleep mode, like I'd expect it to, but doesn't anymore. Don't know if that's the PID changes, display hysteresis, or something else.

As far as tip vs sensor temperature deltas go, I've been thinking that the very end of the tip, at least with the small ones like the "I" and "ILS", is cooler than the more massive body. Makes sense, assuming the heating element is farther away and the small end has more surface area vs volume to radiate from. I have no experience with other high-end soldering irons, but I'm wondering if there's a plating quality issue with the TS100 tips. I'm trying to learn fine-pitch SMD soldering and common advice is to put a tiny blob of solder on the very end of the tip and then touch that to a well-fluxed chip lead and PC board pad.

Problem with at least my "I" and "ILS" tips is when I try to do that the solder "wicks" up to the larger (hotter?) main body of the tip and none of it sticks to the very end. Apologies for this long rant, but bringing it back to firmware and PID algorithms, could there be any way to track the observed sensor time-vs-temp response curve and adaptively tweak the PID constants in real time to try to adjust for different tip's thermal behavior (and environmental conditions)?

**Comment by vifino** [comment] 2017-10-05 08:09
@Ralim No, I mean, it heats a bit faster, I believe. :)

strlen does not sound like macros... But it doesn't matter, those are micro optimizations for things that don't really matter, the chip in the ts100 is more than capable.

Regarding the temperature display jump in the first few fractions of a second, I believe it could indeed be just a little disconnect for a few milliseconds. I tried to reproduce it again, but it worked fine now.

Interestingly, my issue regarding text overwriting also disappeared... Now it's just starting over like it should.

Not sure if it is my iron acting up, the firmware having bugs in it or a faulty supply/flickers...

**Comment by vifino** [comment] 2017-10-05 08:15
Oh, and regarding the advanced display for the soldering mode: Similar to what you have now in the main screen, voltage, temperature, set temperature, heating output in percentage, stuff like that.

I also figured out the weird 500 degree celsius issue by enabling the advanced display: It was a bad calibration. Now it's all good. Just the description text remains a mystery to me.

**Comment by Ralim** [comment] 2017-10-05 12:27
@thanks4opensource 

The PID *should* be faster, but the whole system is different style (it's now uncoupled and different non-syncronized timing). So not really sure how to compare that honestly :smile: 
The not showing the heat icon is most likely down to a bit of PID tuning (The PID is currently tuned for good stability at the cost of a slight increase in response time). Should still be damn quick from my testing, but if its an issue let me know and I can spend another night tuning :grin: 

I don't think its a plating quality issue, I use the C1 (ILS's twin) for all of my SMD and I have found the slight slant on the tip helps, but really what we need for soldering SMD is a J tip rather than the fine ones. I would advise looking at the "tack a pin, flood, solder wick" style where possible :smile: 
I can say that the C1 tip is a lot nicer than most of the Weller tips I have on my WESD51 on the other bench that's for sure. One trick I use is to have the blob on the side of the tip and bring the tip down parallel to the pin from above sometimes works well, oh, and flood with flux :grin: 

Basically, yes but its hard and I don't have the time to spend on that to gain ~0.5 seconds of faster heating on an iron that already beats a lot of them. The payoff usually seems too small for me to put the time into an autotuner that doesn't get in the way.

Currently, I tune for the larger tips but I check on my C1 tipped iron before I ship it (as I use that iron more, but the development iron has a B2 tip in it).

@vifino 
Thanks, that's what I was hoping to achieve in 2.x

strlen is not a macro but its a tiny cost for being a lazy programmer :stuck_out_tongue: 

If you chuck your ideas for an advanced soldering display into its own issue Ill add it in the next 2.x alpha if I can :)

USB power shouldn't affect the calibration, but It does need the tip to be equal to the handle temp, so if you have been holding the handle for ages, for example, its a bit out of whack (though ~5 C is nothing really on the temps you normally solder at, but accuracy is nice to have).

I will be spending more time on the calibration stuff, and so as more users use the feature I will look to see how it goes.

500C is odd, since the way the electronics are set up we can only measure up to ~465C (Thus the 450C hard limit). Normally if the unit sees > 450C for more than ~ 1 second it should trigger disconnected tip so not sure how that happened :s

**Comment by vifino** [comment] 2017-10-05 23:08
@Ralim I don't know either, but a recalibration fixed it, so that's all I care about. :)

While I would always love faster/better/fancier things and features, v2 definitly satisfies most if not all my needs and wishes. I do look forward to what you can come up with, definitly including the advanced solder mode, as I believe it to be much more useful than the regular one, voltage sag would be nice to notice, or a lipo's voltage. :)
Please do make it seperate from the ADVDISP thing, as I do not really like it most of the time, since it does not give me information I need pre-soldering.

Of course, if you find a way to magically make it even faster/accurate at holding temperature/learning from reaction of the tip, it'd be insanely awesome, but really, it's definitly not required as it is already very good. 

I usually use the standard or the ILS tip, as I am doing work ranging from small (building quadcopters and fixing simpler things) to tiny (SMD soldering and such, mostly fixing). Definitly works fine!

Keep up the great work! I might contribute in the future, but so far, I don't see anything I consider to be important to be fixed right away. (That's a very good thing!)

**Comment by discip** [comment] 2022-04-23 15:40
@perillamint
Please close this Issue, since this is finally done [IronOS-dfu](https://github.com/Ralim/IronOS-dfu). 😊

thanks

**Closed** 2022-04-23 16:54 UTC
