### ISSUE TITLE
About TS101 Software

### ISSUE THREAD

**Issue by Alsheikhy** [Ralim/IronOS#1470] opened 2022-11-12 16:18 UTC
Hello, 

   I was looking to buy a soldering iron, after I saw that you have programed this TS100, I was interested to buy one of the best soldering irons out there, so I decided to buy the TS101, because it's the latest, also more powerful than the TS80.

I tried to find a software but I can't find one:).
Are you planning on doing one?

Sincerely,

**Comment by ImmortalScientist** [comment] 2022-11-12 20:05
Duplicate of #1420 

Ralim seems to be working on it already :)

**Comment by Ralim** [comment] 2022-11-12 23:26
Closing as this is a duplicate.

**Closed** 2022-11-12 23:26 UTC
Labels: enhancement
